openapi: 3.0.2
info:
  title: Example
  description: "Based the project on https://reflectoring.io/spring-boot-openapi/"
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
tags:
- name: user
  description: Operations about user
  externalDocs:
    description: Find out more about our store
    url: http://swagger.io
paths:
  /examples/{exampleId}:
    get:
      operationId: getExample
      tags:
        - example
      parameters:
        - name: exampleId
          in: path
          description: Path parameter that identifies the example.
          required: true
          schema:
            type:
              string
      responses:
        200:
          description: Everything went right, return the example.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/example_schema"
  /examples:
    get:
      operationId: getExamples
      tags:
        - examples
      parameters:
        - name: listHasItems
          in: query
          required: false
          description: Optional parameter to test the non existing use case.
          schema:
            type: boolean
      responses:
        200:
          description: Everything went right.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/examples_list"
    put:
      operationId: updateExample
      requestBody:
        description: The object to update.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/example_schema"
      responses:
        200:
          description: Success.
components:
  schemas:
    example_schema:
      type: object
      properties:
        result:
          type: string
        timestamp:
          type: string
          description: Timestamp in ISO-8601 format.
    examples_list:
      type: array
      items:
        $ref: "#/components/schemas/example_schema"
